name = "auth"
main = "dist/worker.mjs"
compatibility_date = "2022-07-29"
usage_model = "unbound"
account_id = ""

[build]
command = "npm run build"
watch_dir = [
  "src",
  "lib"
]

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.mjs"]
