name = "zig-worker-template"
main = "dist/worker.mjs"
compatibility_date = "2022-07-29"
usage_model = "bundled"
account_id = ""

[env]
KEY = "VALUE"

kv_namespaces = [
  { binding = "TEST_NAMESPACE", id = "", preview_id = "testid" }
]

r2_buckets = [
  { binding = "TEST_BUCKET", bucket_name = "test-bucket", preview_bucket_name = "dev-test" }
]

d1_databases = [
  { binding="TEST_DB", database_name="testdb", database_id="", preview_database_id="" }
]

[build]
command = "npm run build:zig && npm run build:esm"
watch_dir = [
  "src",
  "lib"
]

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.mjs"]
